homeassistant:
#  latitude: !secret lat
#  longitude: !secret long
#  elevation: 430
#  unit_system: imperial
#  time_zone: America/New_York
#  name: !secret name
#  customize: !include customize.yaml


##########################################################
## Remote Access & IP Ban
##########################################################


http:
  ip_ban_enabled: true
  login_attempts_threshold: 3


##########################################################
## Themes
##########################################################


frontend:
  themes: !include_dir_merge_named themes


##########################################################
## Python Scripts
##########################################################


python_script:

  
##########################################################
## Z-Wave
##########################################################


zwave:
  network_key: !secret zwave_key

##########################################################
## Device Tracking
##########################################################


device_tracker:
  - platform: nmap_tracker
    hosts: 
      - !secret nmap_host1
      - !secret nmap_host2
    exclude:
     - !secret nmap_host_exclude 


##########################################################
## History & Recorder Settings
##########################################################


#influxdb:
#  database: hass_db
#  username: !secret influxdb_username
#  password: !secret influxdb_password


##########################################################
## Notifications
##########################################################


telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret chat_id


notify:
  - name: NOTIFIER_NAME
    platform: telegram
    chat_id: !secret chat_id


##########################################################
## TTS
##########################################################


tts:
  - platform: google_translate


##########################################################
## Defaults
##########################################################


default_config:
stream:
ffmpeg:
tplink:


##########################################################
## Logging
##########################################################


logger:
  default: info


##########################################################
## Discovery
##########################################################


discovery:
  ignore:
    - homekit


##########################################################
## Open Garage
##########################################################

cover:
  platform: opengarage
  covers:
    garage:
      host: !secret opengarage_host
      device_key: !secret opengarage_key
      name: Garage Door

##########################################################
## MQTT 
##########################################################


mqtt:
  broker: !secret mqtt_broker
  client_id: homeassistant
  username: !secret mqtt_username
  password: !secret mqtt_password  
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'


##########################################################
## Spotify
##########################################################

    
spotify:
  client_id: !secret spotify_client
  client_secret: !secret spotify_secret


##########################################################
## Air Quality Monitoring 
##########################################################


airvisual:
  api_key: !secret airvisual_key
  geographies:
    latitude: !secret lat
    longitude: !secret long


##########################################################
## Include YAML's
##########################################################


group: !include groups.yaml
automation: !include automations.yaml
script: !include_dir_merge_list scripts/
switch: !include_dir_merge_list switches/
sensor: !include_dir_merge_list sensors/
binary_sensor: !include_dir_merge_list binary_sensors/
light: !include_dir_merge_list lights/
yeelight: !include lights/yeelights.yaml
camera: !include_dir_merge_list cameras/
media_player: !include media_player.yaml
input_boolean: !include input_boolean.yaml