homeassistant:
  latitude: !secret lat
  longitude: !secret long
  elevation: 430
  unit_system: imperial
  time_zone: America/New_York
  name: !secret name
  customize: !include customize.yaml


##########################################################
## Remote Access & IP Ban
##########################################################


http:
  base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 3


##########################################################
## Themes
##########################################################


frontend:
  themes: !include_dir_merge_named themes
  javascript_version: latest


##########################################################
## Python Scripts
##########################################################


python_script:


##########################################################
## Device Tracking
##########################################################


device_tracker:
  - platform: nmap_tracker
    hosts: 
      - !secret nmap_host1
      - !secret nmap_host2
    exclude:
     - !secret nmap_host_exclude 


##########################################################
## History & Recorder Settings
##########################################################


history: 
  include:
    domains:
      - light
      - media_player
      - person
      - sensor
      - binary_sensor
      - image_processing  
  exclude:
    entities:
      - sensor.yr_symbol
      - sun.sun
      - sensor.time
      - sensor.sunrise
      - sensor.sunset
      - sensor.date
      - sensor.custom_card_tracker

      
recorder:
  include:
    domains:
      - light
      - media_player
      - person
      - sensor
      - binary_sensor
      - image_processing  
  exclude:
    entities:
      - sensor.yr_symbol
      - sun.sun
      - sensor.time
      - sensor.sunrise
      - sensor.sunset
      - sensor.date
      - sensor.custom_card_tracker
  purge_interval: 0

influxdb:
  database: hass_db
  username: !secret influxdb_username
  password: !secret influxdb_password
  include:
    domains:
      - light
      - media_player
      - person
      - sensor
      - binary_sensor
      - image_processing  
  exclude:
    entities:
      - sensor.yr_symbol
      - sun.sun
      - sensor.time
      - sensor.sunrise
      - sensor.sunset
      - sensor.date
      - sensor.custom_card_tracker


##########################################################
## Notifications
##########################################################


telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret chat_id


notify:
  - name: NOTIFIER_NAME
    platform: telegram
    chat_id: !secret chat_id


##########################################################
## TTS
##########################################################


tts:
  - platform: google_translate


##########################################################
## Defaults
##########################################################


default_config:
stream:
ffmpeg:
tplink:

##########################################################
## Owntracks
##########################################################


owntracks:
  max_gps_accuracy: 150


##########################################################
## Logging
##########################################################


logger:
  default: info


##########################################################
## Discovery
##########################################################


discovery:
  ignore:
    - homekit


##########################################################
## Weather
##########################################################


weather:
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily


##########################################################
## MQTT 
##########################################################


mqtt:
  broker: !secret mqtt_broker
  client_id: homeassistant
  username: !secret mqtt_username
  password: !secret mqtt_password  
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'


##########################################################
## Air Quality Monitoring 
##########################################################


iqvia:
  zip_code: !secret zip

airvisual:
  api_key: !secret airvisual_key
  geographies:
    latitude: !secret lat
    longitude: !secret long


##########################################################
## Include YAML's
##########################################################


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include_dir_merge_list switches/
sensor: !include_dir_merge_list sensors/
binary_sensor: !include_dir_merge_list binary_sensors/
light: !include_dir_merge_list lights/
yeelight: !include lights/yeelights.yaml
camera: !include_dir_merge_list cameras/
media_player: !include media_player.yaml
input_boolean: !include input_boolean.yaml