##########################################################
## Mi Flora
##########################################################


- platform: miflora
  mac: !secret plant_mac
  name: Office Plant
  force_update: true
  median: 3